### ISSUE TITLE
[BUG] Notification text cutoff

### ISSUE THREAD

**Issue by germanfr** [zagortenay333/numix-cinnamon#19]
The screenshot talks by itself.

![screenshot from 2017-01-27 19-34-15](https://cloud.githubusercontent.com/assets/10391266/22382912/f202bec6-e4c7-11e6-8347-1ac2d3659397.png)

This bug is also present in new-minty, ciliora-x and zukitwo.

**Comment by zagortenay333** [comment]
Should be fixed with 13388f7.

**Comment by germanfr** [comment]
It has improved a bit, but still not solved :(

![screenshot from 2017-01-28 12-16-18](https://cloud.githubusercontent.com/assets/10391266/22396214/cfeb30c0-e553-11e6-8144-5c8e54691561.png)

**Comment by zagortenay333** [comment]
Does this happen only with my themes? Oh and, where did this notification come from?

If you have `inotify-tools` installed can you execute something like:
```sh
notify-send "blabl" "blabla"
```

I don't have this issue right now.
![workspace 2_001](https://cloud.githubusercontent.com/assets/11144630/22397838/e63f1248-e57a-11e6-8283-7d1cc584a18b.png)

**Comment by germanfr** [comment]
Yes, I've only seen it on your themes. The notification came from Spotify but the same problem arises with `notify-send`:
Zukitwo notification:
![screenshot from 2017-01-28 17-56-13](https://cloud.githubusercontent.com/assets/10391266/22398201/c0a0fbba-e583-11e6-91d0-1d6e3c7f404e.png)
Zukitwo notification applet:
![screenshot from 2017-01-28 17-55-49](https://cloud.githubusercontent.com/assets/10391266/22398202/c0a4e59a-e583-11e6-9a47-c87d4ab8a323.png)
Default theme:
![screenshot from 2017-01-28 17-59-12](https://cloud.githubusercontent.com/assets/10391266/22398200/c09fb822-e583-11e6-8027-0c5a944868dc.png)

The text is not aligned with the title. I think that's why it's cut.

**Comment by zagortenay333** [comment]
Mind checking out the https://github.com/zagortenay333/numix-cinnamon/tree/notification-fix branch to see if it's fixed now?

**Comment by germanfr** [comment]
Checked it, but that didn't solve it, sorry.

**Comment by zagortenay333** [comment]
I don't understand why it works on my machine and not on yours..

What cinna version do you have?

**Comment by germanfr** [comment]
I don't know. Maybe its the resolution. I'm on 3.2.8 and my res is 1366x768

**Comment by zagortenay333** [comment]
Can you check it out now?
The issue is that I want to add a padding between the time stamp and the title and message and using padding apparently doesn't work on your machine. Maybe using the border property might solve it.

**Comment by zagortenay333** [comment]
If it doesn't work now, the last thing I might try is to replace em's with pixels; otherwise, I'm gonna have to remove the padding from there. :cry:

**Comment by germanfr** [comment]
It doesn't work sorry. :(

**Comment by zagortenay333** [comment]
Alright then try now. I replaced em's with px's.

**Comment by germanfr** [comment]
Nope it still deosn't :sob:

**Comment by zagortenay333** [comment]
Bruuuuuuh :sob:

**Comment by zagortenay333** [comment]
Ok, I removed the padding. Please tell me that this works.

**Comment by germanfr** [comment]
No, it doesn't. I definitely don't know. 
![screenshot from 2017-01-28 23-34-09](https://cloud.githubusercontent.com/assets/10391266/22400366/dea04286-e5b2-11e6-85fd-a3f8fd083509.png)

**Comment by zagortenay333** [comment]
Wait, what? I removed the padding completely on that notification branch. Did you check that one out?

**Comment by germanfr** [comment]
Yeah, I'm on that branch. Your changes must not be taking effect on what you think.

**Comment by germanfr** [comment]
I definitely have the changes because I've done a clean clone right now. But it looks like in the previous screenshot.

**Comment by zagortenay333** [comment]
I'm afraid I can't help you then. You're gonna have to see what in the other themes compared to mine is causing this.

Look into this module https://github.com/zagortenay333/numix-cinnamon/blob/notification-fix/Numix-Cinnamon/cinnamon/scss/main/_notifications.scss#L16-L25

**Comment by germanfr** [comment]
It's not anything from the notifications.scss. I completely removed the content from there and it is still cut.
![screenshot from 2017-01-29 00-10-24](https://cloud.githubusercontent.com/assets/10391266/22400510/79965c22-e5b7-11e6-97cb-f9419f0df3b0.png)

**Comment by zagortenay333** [comment]
Can you try changing the font? The default is set to Roboto.

**Comment by zagortenay333** [comment]
You could also try commenting out one module after another till the bug is gone.
https://github.com/zagortenay333/numix-cinnamon/blob/master/Numix-Cinnamon/cinnamon/scss/cinnamon.scss

**Comment by germanfr** [comment]
Without `@import "main/controls/0-INDEX";` it works, although it's pretty ugly.

**Comment by zagortenay333** [comment]
Screenshot?

**Comment by zagortenay333** [comment]
Also, do the same with the controls module. Disable one after the other to pin it down.
https://github.com/zagortenay333/numix-cinnamon/blob/master/Numix-Cinnamon/cinnamon/scss/main/controls/_0-INDEX.scss

**Comment by germanfr** [comment]
It turns basically into the default theme.

![screenshot from 2017-01-29 00-38-39](https://cloud.githubusercontent.com/assets/10391266/22400659/778b8dea-e5bb-11e6-98a6-cad63e0fcab1.png)

**Comment by oliveiraev** [comment]
I'm OK with [HEAD](/zagortenay333/numix-cinnamon)

![image](https://cloud.githubusercontent.com/assets/320460/22517132/4b14b314-e88f-11e6-9b51-e14792f1c2b3.png)

**Comment by germanfr** [comment]
This is weird. I don't understand why does this happens to me only.

**Comment by zagortenay333** [comment]
What distro are you on?

**Comment by germanfr** [comment]
I'm on Manjaro Cinnamon 3.2.8, resolution 1366x768. It may be a bug introduced in a new version of cinnamon, or it's related with the screen resolution and pixels. @oliveiraev what cinnamon version are you running?

**Comment by zagortenay333** [comment]
Thing is that I can reproduce the way your notifs look like by adding different paddings to the title(bold text) and the message.
![workspace 2_002](https://cloud.githubusercontent.com/assets/11144630/22519443/8c3e0d74-e8b0-11e6-99e8-51e87a167352.png)

Code in the notification module:
```scss
CinnamonGenericContainer * {
    // time status
    color: $text-secondary;
    padding-top: 0;

    // title
    &:first-child {
        color: $text-primary;
        padding-top: .2em;
    }

    // message
    &:last-child {
        color: $text-primary;
        padding-top: .5em;
    }
}
```

**Comment by germanfr** [comment]
I don't know man. I've just checked it again. I removed everything, I cloned it, I switched to the fix branch, and I run watch; but it still looks the same.

**Comment by germanfr** [comment]
And it happens in all your themes I have intalled and in one theme that also uses Roboto as font. It is no longer in the spices, but it can be still downloaded from this old link: [newton-cinnamon](https://cinnamon-spices.linuxmint.com/uploads/themes/13LF-IR8Z-7V7M.zip).

If I change the font to sans-serif it works, but not every font works.

**Comment by zagortenay333** [comment]
Ah, so it is the font's fault after all.
Can you try using some other theme (not mine) while adding roboto to it?

**Comment by oliveiraev** [comment]
> I'm on Manjaro Cinnamon 3.2.8, resolution 1366x768. It may be a bug introduced in a new version of cinnamon, or it's related with the screen resolution and pixels. @oliveiraev what cinnamon version are you running?

```cinnamon --version
Cinnamon 3.2.7```

also on 1366x768...

![image](https://cloud.githubusercontent.com/assets/320460/22520848/0b8c35ec-e89d-11e6-93f0-5906e6f96293.png)

 but Linux Mint. Maybe font hinting settings?
I'm with Linux Mint defaults

```
Noto Sans Regular 9
Noto Sans Regular 10
Noto Sans Regular 10
Source Code Pro for Powerline Regular 10
Noto Sans Bold 10
```

**Comment by germanfr** [comment]
I tried Linux Mint and Mint-X. They go wrong with Roboto.

With Noto Sans (without modifications):
![screenshot from 2017-02-01 19-50-04](https://cloud.githubusercontent.com/assets/10391266/22521309/eddfddd0-e8b7-11e6-83e3-2447903ad968.png)

With Roboto:
![screenshot from 2017-02-01 19-49-24](https://cloud.githubusercontent.com/assets/10391266/22521308/edda26e2-e8b7-11e6-9c4b-24e78841a1c4.png)

**Comment by zagortenay333** [comment]
Well, then it's a bug with cinnamon and not the theme. Closing this.

I'm on cinna `3.2.7`. Maybe when I update to `3.2.8` I might get the same issue.
